# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Portfolio CI

on:
  push:
    branches: ["Development","production","testing","staging"]
  pull_request:
    branches: ["Development","production","testing","staging"]

jobs:
  build:
    runs-on: self-hosted
  steps:
  - name: Set environment variable
    run: echo "API_KEY=${{ secrets.staging }}" >> $GITHUB_ENV
  - name: Use environment variable
    run: |
          echo "The API key is: $API_KEY"
          # Output: The API key is: abcdef123456

    strategy:
      matrix:
        node-version: [18.x]


    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm CI
      - run: npm build